version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
